Task/dummy data added
zsdominik/imdbproject pull request #1
Opened 2020-08-30 11:16 UTC by milanfasi94

-dummy data with movie tvseries class

2020-08-30 18:14 UTC, zsdominik requested changes

2020-08-30 18:14 UTC, zsdominik commented on src/main/java/com/example/imdb/model/Genre.java
> +import javax.persistence.*;
Don't use wildcard imports. This will import the whole package which is unnecessary and not a good practice. It can mess up namespaces:
https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

2020-08-30 18:14 UTC, zsdominik commented on src/main/java/com/example/imdb/model/Tvseries.java
> +public class Tvseries {
I would reconsider this whole concept. The fields of the `TvSeries` are almost identical with the `Movie` you juse expanded it with the `finished` property (which otherwise you should call `isFinished`). 

Why don't just make a Movie or a BaseMovie class and inherit a TvSeries from it? Now almost all of the fields are redundant in both classes.

2020-09-01 13:09 UTC, milanfasi94 commented on src/main/java/com/example/imdb/controller/MovieController.java
> +    }
This changes will be in the task/crud. I remove crud parts from this task branch except getall ( findall())

2020-09-01 13:09 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/EGenre.java
> +import javax.persistence.Enumerated;
Ready

2020-09-01 13:18 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/EGenre.java
> +    Drama,
I took your advice. I removed the whole enum concept and changed the variable type to String and Deleted the Egenre  Enum class

2020-09-01 13:22 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Genre.java
> +    private Set<Movie> Movies = new HashSet<>();
Ready

2020-09-01 13:22 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Genre.java
> +    private Set<Tvseries> Tvseries = new HashSet<>();
Ready

2020-09-01 15:53 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Tvseries.java
> +
Ready

2020-09-01 19:43 UTC, milanfasi94 commented on src/main/java/com/example/imdb/service/MovieService.java
> +    }
I'll make this task in the CRUD branch

2020-09-03 07:41 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Tvseries.java
> +    private Boolean finished = Boolean.TRUE;
Solved.

2020-09-03 08:02 UTC, milanfasi94 commented on src/main/java/com/example/imdb/controller/MovieController.java
> +@RequestMapping("/api")
done

2020-09-03 08:06 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Genre.java
> +@Data
changed

2020-09-03 08:15 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Genre.java
> +import javax.persistence.*;
Now i see. But more then 5 annotation used the persistence and its autogenerated the import. i'll be more observent

2020-09-03 09:06 UTC, milanfasi94 commented on src/main/java/com/example/imdb/controller/MovieController.java
> +@RequestMapping("/api")
If i remove the getmapping("/movies") and change it to @RequestMapping("/api/movies") the swagger is empty as well as from the url localhost:8080/api/movies shows me the sample message. So I kept the original version

2020-09-03 09:11 UTC, milanfasi94 commented on src/main/resources/application.properties
> +spring.data.rest.basePath=/api
i removed it, and when i was testing the changes i realized that the api send me an error messange. The problem was the manytomany joining. I used a JsonIgnore annotation. Hope they are correct in those situations.

2020-09-06 07:14 UTC, milanfasi94 commented on src/main/java/com/example/imdb/model/Tvseries.java
> +public class Tvseries {
I was trying like all the Inheritation strategy, and finally i created a BaseMedia superclass with MappedSuperclass annotation.

2020-09-06 18:31 UTC, zsdominik commented on src/main/java/com/example/imdb/controller/MovieController.java
> +@RequestMapping("/api")
`@RequestMapping("/api/movies")
public class MovieController {

    private final MovieService movieService;

    public MovieController(MovieService movieService) {
        this.movieService = movieService;
    }

    @GetMapping("/")
    public List<Movie> getAllMovies() {
        return movieService.getAllMovies();
    }
}`

it works this way

2020-09-06 18:37 UTC, zsdominik commented on src/main/java/com/example/imdb/model/Genre.java
> +@Data
you should change that everywhere else like BaseMedia.java, Movie.java etc..
Check this article about immutability https://www.baeldung.com/java-immutable-object

2020-09-06 18:40 UTC, zsdominik commented on src/main/java/com/example/imdb/model/Tvseries.java
> +public class Tvseries {
good job

2020-09-06 18:44 UTC, zsdominik approved these changes
please check the two unresolved comments. just minor changes. after that you can merge this

2020-09-06 20:15 UTC, merged